/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proceso;

import java.awt.Font;
import java.awt.Rectangle;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Usuario
 */
public class Ingresar extends javax.swing.JInternalFrame {
    public static String cuenta;
    public static String clave;
    

    /**
     * Creates new form Ingresar
     */
    public Ingresar() {
        initComponents();
        setTitle("Ingreso");
        setBounds(new Rectangle(85, 64, 367, 208));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        txtCuentaingre = new java.awt.TextField();
        txtClaveingre = new org.edisoncor.gui.passwordField.PasswordField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresar");

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4-min.jpg"))); // NOI18N

        labelMetric1.setText("Numero de Cuenta");

        labelMetric2.setText("Clave");

        txtCuentaingre.setName("txtCuentaingre"); // NOI18N
        txtCuentaingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaingreActionPerformed(evt);
            }
        });

        txtClaveingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveingreActionPerformed(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(txtClaveingre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCuentaingre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCuentaingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClaveingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaingreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaingreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaingreActionPerformed

    private void txtClaveingreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveingreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveingreActionPerformed

    public String getCedula(String nCuenta){
        String cdl = "";
        try{
            String consulta= "select DNI fro usuario where `Numero de cuenta`= "+nCuenta;
            Statement sta = Conexion.conexion.createStatement();
            ResultSet rs= sta.executeQuery(consulta);
            if(rs.next()){
                cdl = rs.getInt(1)+"";
            }
        }catch(Exception ex){
            Util.mensaje(this, ex.getMessage(), "Error", "src/Imagenes/descarga.jpg");
        }
        return cdl;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Conexion con = Conexion();
        // TODO add your handling code here:
        
        try{
            if (txtCuentaingre.getText().isEmpty()){throw new Exception("El campo de la cuenta\nesta vacio");}
            if (txtClaveingre.getText().isEmpty()){throw new Exception("El campo de la clave\nesta vacio");}
            if(Util.tieneLetras(txtCuentaingre.getText())){throw new Exception("El campo de la cuenta\nsolo acepta numeros");}
             if(txtClaveingre.getText().length()!=4){throw new Exception("La clave solo puede contener\n4 caracteres");}
             
             cuenta=txtCuentaingre.getText();
             clave=txtClaveingre.getText();
             String s="";
             String consulta = "Select Clave from  usuario where `Numero de cuenta`="+cuenta;
             Conexion.sentencia = Conexion.conexion.createStatement();
             ResultSet rs = Conexion.sentencia.executeQuery(consulta);
             while(rs.next()){
                 if(clave.equals(rs.getString("Clave"))==false){
                     throw new Exception("CLAVE INCORRECTA!!!");
                 }
             }
             Inicio.habilitar = true;
             Inicio.titulo="Cuenta - "+getNombre(cuenta);
             Util.mensaje(this, "Bienvenido..", "Exito", "src/Imagenes/descarga.jpg");
             dispose();
                } catch (Exception ex) {
            Util.mensaje(this, ex.getMessage(), "Error", "src/Imagenes/descarga.jpg");
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.passwordField.PasswordField txtClaveingre;
    private java.awt.TextField txtCuentaingre;
    // End of variables declaration//GEN-END:variables

    private Conexion Conexion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
