/*, 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proceso;

import java.awt.Font;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Inicio extends javax.swing.JFrame {
            public static boolean habilitar =false;
            public static String titulo;
            public static String resumen;
            
            
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setBounds(new Rectangle(900, 600));
        setLocationRelativeTo(null);
        setTitle("Sistema de Cuenta de Ahorros");
        txtresumen.setFont(new Font("Maiandra GD", Font.BOLD, 13));
        habilitarCampos(habilitar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresumen = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        meDepositar = new javax.swing.JMenuItem();
        meRetirar = new javax.swing.JMenuItem();
        meTransferir = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        meEliminar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        meLogout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4-min.jpg"))); // NOI18N
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel1MouseEntered(evt);
            }
        });

        txtresumen.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        txtresumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtresumenMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(txtresumen);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 254, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagina-de-inicio.jpg"))); // NOI18N
        jMenu1.setText("Inicio");

        jMenuItem2.setText("Nuevo Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Ingresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/herramientas-seo.jpg"))); // NOI18N
        jMenu2.setText("Operaciones");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });

        meDepositar.setText("Depositar");
        meDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meDepositarActionPerformed(evt);
            }
        });
        jMenu2.add(meDepositar);

        meRetirar.setText("Retirar");
        meRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meRetirarActionPerformed(evt);
            }
        });
        jMenu2.add(meRetirar);

        meTransferir.setText("Transferir");
        meTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meTransferirActionPerformed(evt);
            }
        });
        jMenu2.add(meTransferir);
        jMenu2.add(jSeparator2);

        meEliminar.setText("Eliminar Cuenta");
        meEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(meEliminar);
        jMenu2.add(jSeparator3);

        meLogout.setText("Cerrar Sesion");
        meLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(meLogout);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jMenu3.setText("Ayuda");

        jMenuItem9.setText("Deposito");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Retiro");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Transferencia");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);
        jMenu3.add(jSeparator4);

        jMenuItem12.setText("Integrantes");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void habilitarCampos(boolean aux){
    if(aux){
        meDepositar.setEnabled(true);
        meRetirar.setEnabled(true);
        meTransferir.setEnabled(true);
        meEliminar.setEnabled(true);
        meLogout.setEnabled(true);
              
    }else{
        meDepositar.setEnabled(false);
        meRetirar.setEnabled(false);
        meTransferir.setEnabled(false);
        meEliminar.setEnabled(false);
        meLogout.setEnabled(false);
    }
}
    
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
             // TODO add your handling code here:
             Nuevo nu=new Nuevo();
             panel1.add(nu);
             nu.show();
             
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void meTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meTransferirActionPerformed
        // TODO add your handling code here:
         Transferencia tra=new Transferencia();
             panel1.add(tra);
             tra.show();
    }//GEN-LAST:event_meTransferirActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
           JOptionPane.showMessageDialog(this,
                "El proceso de la transferencia une las dos funciones anteriores en una sola:\n"+
                "Primeramente tendras que indicar tu clave.\n"+
                "Luego indicaras el monto a transferir seguido de la cuenta a\n"+
                "la que quieras transferir tu dinero.Lo que hace es retirar de tu dinero\n"+
                "la cantidad que indiques, siempre que no exceda los 20000, y depositar\n"+
                "a la cuenta que indiques, esa cantidad de dinero.",
                "Transferencia",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/Imagenes/Info_icon_002.svg.png"));
    
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
           JOptionPane.showMessageDialog(this,
                "Grupo: 10\n"+
                "Integrantes:\nFabian Armijos\n"+
                "Juan Matinez\n"+
                "Kleber Muy",
                "Integrantes de Proyecto",
               JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/Imagenes/Info_icon_002.svg.png"));
    
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Ingresar in=new Ingresar();
             panel1.add(in);
             in.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void meDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meDepositarActionPerformed
        // TODO add your handling code here:
         Deposito de=new Deposito();
             panel1.add(de);
             de.show();
    }//GEN-LAST:event_meDepositarActionPerformed

    private void meRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meRetirarActionPerformed
        // TODO add your handling code here:
         Retiro re=new Retiro();
             panel1.add(re);
             re.show();
    }//GEN-LAST:event_meRetirarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "La tarea de deposito se realiza de la siguente manera:\n"+
                "Seleccionas un monto predeterminado para depositar o puedes\n"+
                "tambien ingresar un monto que prefieras, siempre que este\n"+
                "no supere los 20000 dolares americanos",
                "Deposito",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/Imagenes/Info_icon_002.svg.png"));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,
                "La tarea de retiro se realiza de la siguente manera:\n"+
                "Necesitas ingresar nuevamente tu clave para poder verificar\n"+
                "si es que realmente eres tu quien esta manipulando los datos\n"+
                "luego selecciona un monto predeterminado o ingresar otro valor\n"+
                "siempre que este no exceda los 20000 dolares americanos.",
                "Retiro",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/Imagenes/Info_icon_002.svg.png"));
    
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void meLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meLogoutActionPerformed
        // TODO add your handling code here:
        
        Ingresar.cuenta="";
        Ingresar.clave="";
        txtresumen.setText("");
        this.setTitle("Sistema de Cuenta de Ahorros");
        habilitar = false;
        habilitarCampos(habilitar);
        
    }//GEN-LAST:event_meLogoutActionPerformed

    private void meEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meEliminarActionPerformed
        // TODO add your handling code here:
        String cuentaIngresada = JOptionPane.showInputDialog(this, "Ingrese su Clave", "Ingresar", JOptionPane.WARNING_MESSAGE);
        if(!cuentaIngresada.equals(Ingresar.clave)){
            Util.mensaje(this, "Clave Incorrecta", "Error", "src/Imagenes/Info_icon_002.svg.png");
            return;
        }
        int resp = JOptionPane.showConfirmDialog(this, "¿Deseas Eliminar Esta Cuenta?", "Advertencia", JOptionPane.INFORMATION_MESSAGE,
                                                 JOptionPane.YES_NO_OPTION, new ImageIcon("src/Imagenes/descarga.jpg"));
        if(resp !=0){
            return;
        }
        try{
            String delete = "delete from usuario where `Numero de cuenta` = "+Ingresar.cuenta;
            Conexion.sentencia = Conexion.conexion.createStatement();
            Conexion.sentencia.execute(delete);
            Util.mensaje(this, "Se Elimino Correctamente la Cuenta", "Error", "src/Imagenes/Info_icon_002.svg.png");
            txtresumen.setText("");  
            this.setTitle("Sistema de Cuenta de Ahorros");
            Ingresar.cuenta="";
            Ingresar.clave="";
            habilitar = false;
            habilitarCampos(habilitar);
            
        }catch (Exception ex){
            Util.mensaje(this, ex.getMessage(), "Error", "src/Imagenes/Info_icon_002.svg.png");
            
        }
    }//GEN-LAST:event_meEliminarActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2MenuSelected

    private void txtresumenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtresumenMouseEntered
        // TODO add your handling code here:
        habilitarCampos(habilitar);
    }//GEN-LAST:event_txtresumenMouseEntered

    private void panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseEntered
        // TODO add your handling code here:
        Ingresar in= new Ingresar();
        if(habilitar==false){
            return;
        }
        this.setTitle(titulo);
                try {
                    resumen="Resumen------------"+
                            "\nCuenta: "+Ingresar.cuenta+
                            "\nNombre: "+in.getNombre(Ingresar.cuenta)+
                            "\nCedula: "+in.getCedula(Ingresar.cuenta)+
                            "\nSaldo: "+Deposito.getSaldoActual(Ingresar.cuenta);
                } catch (SQLException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
        txtresumen.setText(resumen);
                
    }//GEN-LAST:event_panel1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem meDepositar;
    private javax.swing.JMenuItem meEliminar;
    private javax.swing.JMenuItem meLogout;
    private javax.swing.JMenuItem meRetirar;
    private javax.swing.JMenuItem meTransferir;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTextPane txtresumen;
    // End of variables declaration//GEN-END:variables
}
